#!/usr/bin/env zsh

emulate -L zsh -o extended_glob
local MATCH
LBUFFER=${LBUFFER%%(#m)[-_[:alnum:]]#}
# If matches set abbreviation add that else just add what we attempted to match on.
abbreviation="${ZSH_SIMPLE_ABBREVIATIONS[$MATCH]}"
LBUFFER+=${abbreviation:-$MATCH}
# Causes the syntax highlighting.
zle self-insert
